### PR TITLE
Closes #107

### LINKED ISSUE #107: S3 assets with spaces in the filename cannot be deleted
# The bug

Steps to Reproduce:
1. Navigate to a node in Grashopper Admin
1. Upload a file with a space in the filename
1. Attempt to delete the file

Expected:
The file is deleted

Actual: 
The admin shows a success message, but refreshing the page shows that the asset has, in fact, not been deleted

# The fix
Replace spaces in filenames with a character. Make the character configurable, but default to an underscore ("_")

### PR DESCRIPTION
**Pull request by uselessinfo**
Adds a new configuration value and replaces spaces in filenames when using S3.

I couldn't run the tests on my Windows machine, so if possible, I would recommend pulling and running the test suite before merging.

### CODE REVIEW

File: lib/assets/aws/index.js [hunk 1]
```diff
@@ -15,7 +17,7 @@ module.exports = (function(){
         LOGGING_CATEGORY = 'AWS-ASSET-MANAGER';
 
     internal.buildKey = function(nodeid, filename, prefix) {
-        var result = (internal.config.assetsDir ? internal.config.assetsDir + '/' : '') + nodeid + (filename ? '/' + filename : '');
```
Comment (pajtai) [inline lib/assets/aws/index.js]: `grasshopper` is undefined, and `replace(' '` will only work on the first one. updated to `/\s/g`

Comment (pajtai) [reply lib/assets/aws/index.js]: was able to test that filenameSpaceReplacement works, but for whatever reason the demo app gh admin is sending back `undefined` as the node id whenever I try to delete something... merging since it looks like it should work and then I'll keep working on why the demo repo seems broken.
